export const Configuration = {
  localStorage: {
    SEARCH_HISTORY_KEY: 'SEARCH_HISTORY',
    SEARCH_HISTORY_10SEC_TIMEOUT: 10000,
    SEARCH_HISTORY_10MIN_TIMEOUT: 600000,
    SEARCH_HISTORY_MAX_ELEMENT: 3
  }
};